<a href="https://colab.research.google.com/github/reyvnth/Numpy_fundamentals/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **How to create a numpy array?**

In [ ]:
import numpy as np
list1 = [10,20,30,40,50]
arr1d = np.array(list1)

In [ ]:
print(type(arr1d))

<class 'numpy.ndarray'>


In [ ]:
print(arr1d)

[10 20 30 40 50]


In [ ]:
# Create a 2d array from a list of lists
list2 = [[1,12,23], [34,45,56], [67,78,89]]

arr2d = np.array(list2)
arr2d

array([[ 1, 12, 23],
       [34, 45, 56],
       [67, 78, 89]])

In [ ]:
# Create a float 2d array

arry= np.array(list2, dtype='float')

arry

array([[ 1., 12., 23.],
       [34., 45., 56.],
       [67., 78., 89.]])

In [ ]:
# Convert to 'int' datatype
arry.astype('int')

array([[ 1, 12, 23],
       [34, 45, 56],
       [67, 78, 89]])

In [ ]:
# Convert to int then to str datatype
arry.astype('str')

#> array([['0', '1', '2'],
#>        ['3', '4', '5'],
#>        ['6', '7', '8']],
#>       dtype='U21')

array([['1.0', '12.0', '23.0'],
       ['34.0', '45.0', '56.0'],
       ['67.0', '78.0', '89.0']], dtype='<U32')

In [ ]:
arry.tolist()

[[1.0, 12.0, 23.0], [34.0, 45.0, 56.0], [67.0, 78.0, 89.0]]

Size and shape of a Numpy Array

In [ ]:
# Create a 2d array with 3 rows and 4 columns
list2 = [[11, 22, 33, 44],[33, 44, 55, 66], [55, 66, 77, 88]]
arr2 = np.array(list2, dtype='float')
arr2

array([[11., 22., 33., 44.],
       [33., 44., 55., 66.],
       [55., 66., 77., 88.]])

In [ ]:
# shape
print('Shape: ', arr2.shape)

# dtype
print('Datatype: ', arr2.dtype)

# size
print('Size: ', arr2.size)

# ndim
print('Num Dimensions: ', arr2.ndim)

Shape:  (3, 4)
Datatype:  float64
Size:  12
Num Dimensions:  2


Extract Specific Items from the array

In [ ]:
arr2

array([[11., 22., 33., 44.],
       [33., 44., 55., 66.],
       [55., 66., 77., 88.]])

 Reverse the rows and the whole array

In [ ]:
# Reverse only the row positions
arr2[::-1, ]

array([[55., 66., 77., 88.],
       [33., 44., 55., 66.],
       [11., 22., 33., 44.]])

In [ ]:
# Reverse the row and column positions
arr2[::-1, ::-1]

array([[88., 77., 66., 55.],
       [66., 55., 44., 33.],
       [44., 33., 22., 11.]])

# Compute mean, min, max on the ndarray

In [ ]:
# mean, max and min
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  49.5
Max value is:  88.0
Min value is:  11.0


In [ ]:
# Row wise and column wise min
print("Column wise minimum: ", np.amin(arr2, axis=0))
print("Row wise minimum: ", np.amin(arr2, axis=1))

Column wise minimum:  [11. 22. 33. 44.]
Row wise minimum:  [11. 33. 55.]


In [ ]:
# Cumulative Sum
np.cumsum(arr2)

array([ 11.,  33.,  66., 110., 143., 187., 242., 308., 363., 429., 506.,
       594.])

Creating a new array from an existing array

In [ ]:
# Assign portion of arr2 to arr2a. Doesn't really create a new array.
arr2a = arr2[:2,:2]  
arr2a[:1, :1] = 100  # 100 will reflect in arr2
arr2

array([[100.,  22.,  33.,  44.],
       [ 33.,  44.,  55.,  66.],
       [ 55.,  66.,  77.,  88.]])

In [ ]:
# Copy portion of arr2 to arr2b
arr2b = arr2[:2, :2].copy()
arr2b[:1, :1] = 101  # 101 will not reflect in arr2
arr2

array([[100.,  22.,  33.,  44.],
       [ 33.,  44.,  55.,  66.],
       [ 55.,  66.,  77.,  88.]])

Reshaping and Flattening Multidimensional arrays

In [ ]:
# Reshape a 3x4 array to 4x3 array
arr2.reshape(4, 3)

array([[100.,  22.,  33.],
       [ 44.,  33.,  44.],
       [ 55.,  66.,  55.],
       [ 66.,  77.,  88.]])

Difference between flatten() and ravel()

In [ ]:
# Flatten it to a 1d array
arr2.flatten()

array([100.,  22.,  33.,  44.,  33.,  44.,  55.,  66.,  55.,  66.,  77.,
        88.])

In [ ]:
# Changing the flattened array does not change parent
b1 = arr2.flatten()  
b1[0] = 100  # changing b1 does not affect arr2
arr2

array([[100.,  22.,  33.,  44.],
       [ 33.,  44.,  55.,  66.],
       [ 55.,  66.,  77.,  88.]])

In [ ]:
# Changing the raveled array changes the parent also.
b2 = arr2.ravel()  
b2[0] = 101  # changing b2 changes arr2 also
arr2

array([[101.,  22.,  33.,  44.],
       [ 33.,  44.,  55.,  66.],
       [ 55.,  66.,  77.,  88.]])

Create sequences, repetitions and random numbers using Numpy

In [ ]:
# Lower limit is 0 be default
print(np.arange(11))  



[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 0 to 9
print(np.arange(2, 14))  


[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [ ]:

# 0 to 9 with step of 2
print(np.arange(1, 18, 2))  


[ 1  3  5  7  9 11 13 15 17]


In [ ]:

# 10 to 1, decreasing order
print(np.arange(10, 0, -1))

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# Start at 1 and end at 50
np.linspace(start=1, stop=50, num=14, dtype=int)

array([ 1,  4,  8, 12, 16, 19, 23, 27, 31, 34, 38, 42, 46, 50])

In [ ]:
# Limit the number of digits after the decimal to 2
np.set_printoptions(precision=2)  



In [ ]:
# Start at 10^1 and end at 10^50
np.logspace(start=1, stop=50, num=10, base=10) 

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

In [ ]:
#The np.zeros and np.ones functions lets you create arrays of desired shape where all the items are either 0’s or 1’s.
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Generating Random Numbers

In [ ]:
# Random numbers between [0,1) of shape 2,2
print(np.random.rand(3,3))



[[0.23 0.75 0.37]
 [0.57 0.2  0.69]
 [0.47 0.58 0.88]]


In [ ]:

# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(3,3))



[[ 2.46  1.56  0.07]
 [ 0.51 -2.08 -0.89]
 [ 0.53 -1.3  -0.82]]


In [ ]:
# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 20, size=[3,3]))



[[13 16  1]
 [ 6  8 19]
 [19 17 18]]


In [ ]:
# One random number between [0,1)
print(np.random.random())


0.3986247584737075


In [ ]:
# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[3,3]))


[[0.5  0.66 0.85]
 [0.14 0.17 0.52]
 [0.25 0.05 0.8 ]]


In [ ]:

# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))  


['e' 'a' 'u' 'i' 'o' 'u' 'i' 'o' 'o' 'i']


In [ ]:
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1]))  # picks more o's

['o' 'o' 'o' 'a' 'i' 'o' 'o' 'u' 'o' 'a']


In [ ]:
# Create the random state
rn = np.random.RandomState(100)

# Create random numbers between [0,1) of shape 2,2
print(rn.rand(2,2))

[[0.54 0.28]
 [0.42 0.84]]


In [ ]:
# Set the random seed
np.random.seed(100)

# Create random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

[[0.54 0.28]
 [0.42 0.84]]


Getting the unique items and the counts

In [ ]:
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [ ]:
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [0 2 3 4 5 7 8]
Counts       :  [1 2 1 1 1 2 2]


 Getting index locations that satisfy a given condition using np.where

In [ ]:
# Create an array
import numpy as np
arr_rand = np.array([85, 18, 13, 87, 87, 0, 14, 42, 65, 12])
print("Array: ", arr_rand)


Array:  [85 18 13 87 87  0 14 42 65 12]


In [ ]:

# Positions where value > 5
index_gt5 = np.where(arr_rand > 5)
print("Positions where value > 5: ", index_gt5)

Positions where value > 5:  (array([0, 1, 2, 3, 4, 6, 7, 8, 9]),)


In [ ]:
# Take items at given index
arr_rand.take(index_gt5)

array([[85, 18, 13, 87, 87, 14, 42, 65, 12]])

In [ ]:
# If value > 5, then yield 'gt5' else 'le5'
np.where(arr_rand > 5, 'gt5', 'le5')

array(['gt5', 'gt5', 'gt5', 'gt5', 'gt5', 'le5', 'gt5', 'gt5', 'gt5',
       'gt5'], dtype='<U3')

In [ ]:
# Location of the max
print('Position of max value: ', np.argmax(arr_rand))  


Position of max value:  3


In [ ]:
# Location of the min
print('Position of min value: ', np.argmin(arr_rand))  

Position of min value:  5


Concatenate two numpy arrays columnwise and row wise

In [ ]:
a = np.zeros([5, 5])
b = np.ones([5, 5])
print(a)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Sorting a numpy array based on one or more columns

In [ ]:
arr = np.random.randint(1,6, size=[7, 3])
arr

array([[4, 1, 2],
       [1, 5, 3],
       [1, 1, 3],
       [3, 2, 1],
       [3, 2, 5],
       [3, 1, 4],
       [4, 4, 1]])

In [ ]:
# Sort each columns of arr
np.sort(arr, axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [3, 1, 2],
       [3, 2, 3],
       [3, 2, 3],
       [4, 4, 4],
       [4, 5, 5]])

Sorting a numpy array based on 1 column using argsort

In [ ]:
# Get the index positions that would sort the array
x = np.array([1, 10, 25, 52, 28, 99])
sort_index = np.argsort(x)
print(sort_index)

[0 1 2 4 3 5]


In [ ]:
# In array ‘x’, the 0th item is the smallest, 3rd item is the second smallest and so on.

x[sort_index]

array([ 1, 10, 25, 28, 52, 99])

In [ ]:
# Argsort the first column
sorted_index_1stcol = arr[:, 0].argsort()

# Sort 'arr' by first column without disturbing the integrity of rows
arr[sorted_index_1stcol]

array([[1, 5, 3],
       [1, 1, 3],
       [3, 2, 1],
       [3, 2, 5],
       [3, 1, 4],
       [4, 1, 2],
       [4, 4, 1]])

In [ ]:
# Descending sort
arr[sorted_index_1stcol[::-1]]

array([[4, 4, 1],
       [4, 1, 2],
       [3, 1, 4],
       [3, 2, 5],
       [3, 2, 1],
       [1, 1, 3],
       [1, 5, 3]])

Sorting a numpy array based on 2 or more columns

In [ ]:
# Sort by column 0, then by column 1
lexsorted_index = np.lexsort((arr[:, 1], arr[:, 0])) 
arr[lexsorted_index]

array([[1, 1, 3],
       [1, 5, 3],
       [3, 1, 4],
       [3, 2, 1],
       [3, 2, 5],
       [4, 1, 2],
       [4, 4, 1]])

Working with dates

In [ ]:
# Create a datetime64 object
date64 = np.datetime64('2020-09-15 16:37:35')
date64

numpy.datetime64('2020-09-15T16:37:35')

In [ ]:
# Drop the time part from the datetime64 object
dt64 = np.datetime64(date64, 'D')
dt64

numpy.datetime64('2020-09-15')

In [ ]:
# Create the timedeltas (individual units of time)
tenminutes = np.timedelta64(10, 'm')  # 10 minutes
tenseconds = np.timedelta64(10, 's')  # 10 seconds
tennanoseconds = np.timedelta64(10, 'ns')  # 10 nanoseconds

print('Add 10 days: ', dt64 + 10)
print('Add 10 minutes: ', dt64 + tenminutes)
print('Add 10 seconds: ', dt64 + tenseconds)
print('Add 10 nanoseconds: ', dt64 + tennanoseconds)

Add 10 days:  2020-09-25
Add 10 minutes:  2020-09-15T00:10
Add 10 seconds:  2020-09-15T00:00:10
Add 10 nanoseconds:  2020-09-15T00:00:00.000000010


In [ ]:
# Convert np.datetime64 back to a string
np.datetime_as_string(dt64)

'2020-09-15'

In [ ]:
print('Date: ', dt64)
print("Is it a business day?: ", np.is_busday(dt64))  
print("Add 2 business days, rolling forward to nearest biz day: ", np.busday_offset(dt64, 2, roll='forward'))  
print("Add 2 business days, rolling backward to nearest biz day: ", np.busday_offset(dt64, 2, roll='backward'))  

Date:  2020-09-15
Is it a business day?:  True
Add 2 business days, rolling forward to nearest biz day:  2020-09-17
Add 2 business days, rolling backward to nearest biz day:  2020-09-17


Creating a sequence of dates

In [ ]:
# Create date sequence
dates = np.arange(np.datetime64('2020-09-01'), np.datetime64('2020-09-15'))
print(dates)

# Check if its a business day
np.is_busday(dates)

['2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14']


array([ True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True, False, False,  True])

Convert numpy.datetime64 to datetime.datetime object

In [ ]:
# Convert np.datetime64 to datetime.datetime
import datetime
dt = dt64.tolist()
dt

datetime.date(2020, 9, 15)

In [ ]:
print('Year: ', dt.year)  
print('Day of month: ', dt.day)
print('Month of year: ', dt.month)  
print('Day of Week: ', dt.weekday())  # Sunday

Year:  2020
Day of month:  15
Month of year:  9
Day of Week:  1


Vectorize – Make a scalar function work on vectors

In [ ]:
# Define a scalar function
def foo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2

# On a scalar
print('x = 10 returns ', foo(10))
print('x = 11 returns ', foo(11))


x = 10 returns  5.0
x = 11 returns  121


In [ ]:
# Vectorize foo(). Make it work on vectors.
foo_v = np.vectorize(foo, otypes=[float])

print('x = [10, 11, 12] returns ', foo_v([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] returns ', foo_v([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] returns  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] returns  [[  5. 121.   6.]
 [  1.   1.   9.]]


Apply a function column wise or row wise

In [ ]:
# Create a 4x10 random array
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,6])
arr_x

array([[9, 9, 4, 8, 8, 1],
       [5, 3, 6, 3, 3, 3],
       [2, 1, 9, 5, 1, 7],
       [3, 5, 2, 6, 4, 5]])

In [ ]:
# Define func1d
def max_minus_min(x):
    return np.max(x) - np.min(x)

# Apply along the rows
print('Row wise: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# Apply along the columns
print('Column wise: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Row wise:  [8 3 8 4]
Column wise:  [7 8 7 5 7 6]


Find the location to insert so the array will remain sorted

In [ ]:
# example of searchsorted
x = np.arange(10)
print('Where should 5 be inserted?: ', np.searchsorted(x, 5))
print('Where should 5 be inserted (right)?: ', np.searchsorted(x, 5, side='right'))

Where should 5 be inserted?:  5
Where should 5 be inserted (right)?:  6


In [ ]:
# Randomly choose an item from a list based on a predefined probability
lst = range(10000)  # the list
probs = np.random.random(10000); probs /= probs.sum()  # probabilities

%timeit lst[np.searchsorted(probs.cumsum(), np.random.random())]
%timeit np.random.choice(lst, p=probs)

10000 loops, best of 3: 38.5 µs per loop
1000 loops, best of 3: 1.49 ms per loop


Clip

In [ ]:
# Cap all elements of x to lie between 3 and 8
np.clip(x, 1, 7)

array([1, 1, 2, 3, 4, 5, 6, 7, 7, 7])

**Numpy Exercises**

**1. How to create a 1D array?**

Q. Create a 1D array of numbers from 0 to 9

In [ ]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


**2. How to create a boolean array?**

Q. Create a 3×3 numpy array of all True’s

In [ ]:
print(np.ones((3,3), dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**3. How to extract items that satisfy a given condition from 1D array?**

Q. Extract all odd numbers from arr

Input:

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=[i for i in arr if i%2!=0]
print(a)   

[1, 3, 5, 7, 9]


**4. How to replace items that satisfy a condition with another value in numpy array?**

Q. Replace all odd numbers in arr with -1

Input:

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.where(arr%2==1, -1, arr)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**5. How to replace items that satisfy a condition without affecting the original array?**

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2 = np.where(arr%2==1, -1, arr)
print(arr2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**6. How to reshape an array?**

Q. Convert a 1D array to a 2D array with 2 rows

Input:

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr3 = np.reshape(arr, (2,5))
print(arr3)

[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


**7. How to stack two arrays vertically?**

Q. Stack arrays a and b vertically

Input

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [ ]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**8. How to stack two arrays horizontally?**

Q. Stack the arrays a and b horizontally.

Input

In [ ]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

In [ ]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

**9. How to get the common items between two python numpy arrays?**

Q. Get the common items between a and b

Input:

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

**10. How to remove from one array those items that exist in another?**

Q. From array a remove all items present in array b

Input:

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [ ]:
x = np.intersect1d(a,b)
print(np.delete(a,x))

[1 2 3 4 5]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  


**11. How to get the positions where elements of two arrays match?**

Q. Get the positions where elements of a and b match

Input:

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
np.where(a == b)

(array([1, 3, 5, 7]),)

**12. How to extract all numbers between a given range from a numpy array?**

Q. Get all items between 5 and 10 from a.

Input:

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [ ]:
b = [i for i in a if (i>=5) and (i<=10)]
print(b)

[6, 9, 10]


**13. How to make a python function that handles scalars to work on numpy arrays?**

Q. Convert the function maxx that works on two scalars, to work on two arrays.

Input:

In [ ]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(7, 14)
#> 5

14

In [ ]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([15, 17, 29, 88, 64, 44, 54])
b = np.array([66, 13, 14, 18, 94, 77, 11])

pair_max(a, b)

array([66., 17., 29., 88., 94., 77., 54.])

**14. How to swap two columns in a 2d numpy array?**

Q. Swap columns 1 and 2 in the array arr.

Input:

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[:, [1,0]] = arr[:, [0,1]]
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

**15. How to swap two rows in a 2d numpy array?**

Q. Swap rows 1 and 2 in the array arr:

Input:

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[[0,1], :] = arr[[1,0], :]
arr

array([[4, 3, 5],
       [1, 0, 2],
       [7, 6, 8]])

**16. How to print only 3 decimal places in python numpy array?**

Q. Print or show only 3 decimal places of the numpy array rand_arr.

In [ ]:
#Input:

rand_arr = np.random.random((5,3))

In [ ]:
np.around(rand_arr, decimals = 3)

array([[0.24, 0.2 , 0.08],
       [0.35, 0.63, 0.47],
       [0.07, 0.15, 0.68],
       [0.71, 0.47, 0.38],
       [0.86, 0.81, 0.1 ]])

**17. How to limit the number of items printed in output of numpy array?**

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Input:

In [ ]:
a = np.arange(15)

In [ ]:
np.resize(a,(1,6))

array([[0, 1, 2, 3, 4, 5]])